#
# (C) Copyright 2008-2017 Fuzhou Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += rockchip_display.o rockchip_crtc.o rockchip_vop.o rockchip_vop_reg.o rockchip_phy.o bmp_helper.o

obj-$(CONFIG_DRM_ROCKCHIP_DW_HDMI) += rockchip_dw_hdmi.o
obj-$(CONFIG_ROCKCHIP_INNO_HDMI_PHY) += rockchip-inno-hdmi-phy.o dw_hdmi.o
